//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devil_Survivor_Script_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devil_Survivor_Script_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about this program.
        /// </summary>
        public static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This segment has been automatically translated from memory.
        /// </summary>
        public static string ATtip {
            get {
                return ResourceManager.GetString("ATtip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author:.
        /// </summary>
        public static string authorLabel {
            get {
                return ResourceManager.GetString("authorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy original text to translation for all the file starting in the actual segment until reaching the last one.
        ///(F9).
        /// </summary>
        public static string copyAllText {
            get {
                return ResourceManager.GetString("copyAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy original text to translation
        ///(F1).
        /// </summary>
        public static string copyText {
            get {
                return ResourceManager.GetString("copyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string fileOpen {
            get {
                return ResourceManager.GetString("fileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the Event folder that contains the texts.
        /// </summary>
        public static string fileOpenDesc {
            get {
                return ResourceManager.GetString("fileOpenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is not the folder that contains the files with the texts.
        /// </summary>
        public static string fileOpenErrText {
            get {
                return ResourceManager.GetString("fileOpenErrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Path.
        /// </summary>
        public static string fileOpenErrTitle {
            get {
                return ResourceManager.GetString("fileOpenErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the path of the Event folder.
        /// </summary>
        public static string fileOpenText {
            get {
                return ResourceManager.GetString("fileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open (Ctrl+O).
        /// </summary>
        public static string fileOpenTextSub {
            get {
                return ResourceManager.GetString("fileOpenTextSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string fileSave {
            get {
                return ResourceManager.GetString("fileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have to open the Event folder with the &apos;Open&apos; button before creating the new translated files..
        /// </summary>
        public static string fileSaveErrText {
            get {
                return ResourceManager.GetString("fileSaveErrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string fileSaveErrTitle {
            get {
                return ResourceManager.GetString("fileSaveErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate the new translated files.
        /// </summary>
        public static string fileSaveText {
            get {
                return ResourceManager.GetString("fileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save (Ctrl+S).
        /// </summary>
        public static string fileSaveTextSub {
            get {
                return ResourceManager.GetString("fileSaveTextSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        public static string filesLabel {
            get {
                return ResourceManager.GetString("filesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a number here and press Enter to jump to that segment
        ///(Ctrl+G).
        /// </summary>
        public static string jumpToText {
            get {
                return ResourceManager.GetString("jumpToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lines: .
        /// </summary>
        public static string lines {
            get {
                return ResourceManager.GetString("lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next segment
        ///(F5).
        /// </summary>
        public static string nextSegText {
            get {
                return ResourceManager.GetString("nextSegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Open any file to start&gt;.
        /// </summary>
        public static string openAny {
            get {
                return ResourceManager.GetString("openAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open the file with a text editor.
        /// </summary>
        public static string openInNoteText {
            get {
                return ResourceManager.GetString("openInNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original.
        /// </summary>
        public static string originalLabel {
            get {
                return ResourceManager.GetString("originalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All files have been generated properly in the Output folder.
        /// </summary>
        public static string outputFinishText {
            get {
                return ResourceManager.GetString("outputFinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string outputFinishTitle {
            get {
                return ResourceManager.GetString("outputFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous segment
        ///(F4).
        /// </summary>
        public static string prevSegText {
            get {
                return ResourceManager.GetString("prevSegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating {0} of {1}.
        /// </summary>
        public static string progressText {
            get {
                return ResourceManager.GetString("progressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished!.
        /// </summary>
        public static string progressTextFinished {
            get {
                return ResourceManager.GetString("progressTextFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax error....
        /// </summary>
        public static string syntaxErr {
            get {
                return ResourceManager.GetString("syntaxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add blue text.
        /// </summary>
        public static string tagBlueText {
            get {
                return ResourceManager.GetString("tagBlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add inverted commas.
        /// </summary>
        public static string tagCommasText {
            get {
                return ResourceManager.GetString("tagCommasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string tagLabel {
            get {
                return ResourceManager.GetString("tagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a new text block.
        /// </summary>
        public static string tagNewText {
            get {
                return ResourceManager.GetString("tagNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add yellow text.
        /// </summary>
        public static string tagYellowText {
            get {
                return ResourceManager.GetString("tagYellowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acknowledgements:.
        /// </summary>
        public static string thanksLabel {
            get {
                return ResourceManager.GetString("thanksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DarthNemesis y Nintenlord
        ///(LZ77 compression)
        ///
        ///CUE
        ///(Information about the structure of the files)
        ///
        ///David Fens
        ///(&quot;Devil Survivor&quot; font for Windows)
        ///                
        ///KenshinX
        ///(Russian compatibility)
        ///
        ///Yusuke Kamiyamane
        ///(Icon set).
        /// </summary>
        public static string thanksText {
            get {
                return ResourceManager.GetString("thanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translation.
        /// </summary>
        public static string translationLabel {
            get {
                return ResourceManager.GetString("translationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Words: .
        /// </summary>
        public static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
